from __future__ import annotations

from typing import Any, Protocol


class AccountsRepositoryPort(Protocol):
    def __init__(self, connection) -> None: ...

    def ensure_table(self) -> None: ...

    def list_accounts(self) -> list[dict[str, Any]]: ...

    def upsert_account(self, payload: dict[str, Any]) -> None: ...


class InboxesRepositoryPort(Protocol):
    def __init__(self, connection, *, account_id: int) -> None: ...

    def ensure_table(self) -> None: ...

    def list_inboxes(self) -> list[dict[str, Any]]: ...

    def upsert_inbox(self, payload: dict[str, Any]) -> None: ...


class ConversationsRepositoryPort(Protocol):
    def __init__(self, connection) -> None: ...

    def ensure_table(self) -> None: ...

    def list_conversations(self) -> list[dict[str, Any]]: ...

    def upsert_conversation(self, payload: dict[str, Any]) -> None: ...


class MessagesRepositoryPort(Protocol):
    def __init__(self, connection) -> None: ...

    def ensure_table(self) -> None: ...

    def list_messages(self) -> list[dict[str, Any]]: ...

    def upsert_message(self, payload: dict[str, Any]) -> None: ...
